### ISSUE TITLE
Calling bpy.ops.render.render_still_with_custom_resolution() via python script from command line results in errors.

### ISSUE THREAD

**Issue by mouring** [Gatada/MultiResolutionCameras#2]
My script is simply:

```
import bpy

bpy.ops.wm.open_mainfile(filepath="blenderfile.blend")
save_path = "/tmp"
room_name = "room01"

for i in range(bpy.data.scenes["Scene"].frame_start, bpy.data.scenes["Scene"].frame_end+1, bpy.data.scenes["Scene"].frame_step):
    bpy.context.scene.frame_set(i)
    camera = bpy.data.scenes["Scene"].camera
    file_name = "%s/%s-%02d" % (save_path, room_name, i)

    print("Rendering Frame:", i, "on camera:", camera.name)
    bpy.ops.render.render_still_with_custom_resolution(camera_name=camera.name)
```

Running it with: Blender --python script.py -b

Results in the the first Frame rendering then crashing at the end with:

Traceback (most recent call last):
  File "/Users/mouring/Library/Application Support/Blender/3.6/scripts/addons/jb-multicamera.py", line 809, in execute
    context.area.tag_redraw()
AttributeError: 'NoneType' object has no attribute 'tag_redraw'
Info: Rendering Top Camera - interface will become unresponsive
Error: Python: Traceback (most recent call last):
  File "/Users/mouring/Library/Application Support/Blender/3.6/scripts/addons/jb-multicamera.py", line 809, in execute
    context.area.tag_redraw()
AttributeError: 'NoneType' object has no attribute 'tag_redraw'
Location: /Users/mouring/My Applications/3D Apps/Blender.app/Contents/Resources/3.6/scripts/modules/bpy/ops.py:113
Error: Python: Traceback (most recent call last):
  File "/private/tmp/script.py", line 13, in <module>
    bpy.ops.render.render_still_with_custom_resolution(camera_name=camera.name)
  File "/Users/mouring/My Applications/3D Apps/Blender.app/Contents/Resources/3.6/scripts/modules/bpy/ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/Users/mouring/Library/Application Support/Blender/3.6/scripts/addons/jb-multicamera.py", line 809, in execute
    context.area.tag_redraw()
AttributeError: 'NoneType' object has no attribute 'tag_redraw'
Location: /Users/mouring/My Applications/3D Apps/Blender.app/Contents/Resources/3.6/scripts/modules/bpy/ops.py:113

OS is MacOS running  Blender 3.6.5 (hash cf1e1ed46b7e built 2023-10-18 23:44:49)

Since I can't attach the simple blend file example you can find it here: https://www.dropbox.com/scl/fi/t04sbro71hwuc6wgq2qkq/test.blend?rlkey=pn51hf5l9w0wnr1by9gbryj6p&dl=0

**Comment by mouring** [comment]
Note the issue seems to be related to attempting to call tag_redraw() when blender is set in the background.  The following looks to fix this.  This is lightly tested, but seems to resolve the issue.

```
diff --git a/jb-multicamera.py b/jb-multicamera.py
index 375ec1e..7efcbff 100644
--- a/jb-multicamera.py
+++ b/jb-multicamera.py
@@ -806,7 +806,8 @@ class RENDER_OT_render_custom_resolution(bpy.types.Operator):
                                context.scene.render.resolution_y = original_resolution_y
        
                                # Update the area to refresh the UI
-                               context.area.tag_redraw()
+                               if not bpy.app.background:
+                                       context.area.tag_redraw()
                                
                                self.report({'INFO'}, f"Rendered camera to Blender Render window (may not update automatically)")

```

**Comment by Gatada** [comment]
So the issue is when rendering with Blender using a script?

And your script is calling a method in this add-on to render the frames with the custom resolution? Is that right?

**Comment by Gatada** [comment]
Your suggested solution seems sensible; do not update UI when Blender is in the background.

I'll test it out and merge it unless I see issues. Thanks!

**Comment by Gatada** [comment]
Excellent, this seems to have fixed it, agreed. Thank you for your contribution!

**Comment by mouring** [comment]
> So the issue is when rendering with Blender using a script?
> 
> And your script is calling a method in this add-on to render the frames with the custom resolution? Is that right?

Correct.  I'm effectively minicing:  blender -b -a  blendfile.blend 

Since the frame_change_post isn't automatically setting the resolution_x and resolution_y up.  And after spending a few hours trying to force it to do it.  I just gave up and wrote my own -a python equalivent using your bpy.ops.render.render_still_with_custom_resolution() function call in a loop.

**Comment by Gatada** [comment]
I was able to run your initially posted script, and it rendered correctly.

Did you try the latest version?

Also new feature in the UI: render animation with scene camera (see Animation panel).

**Comment by mouring** [comment]
Sorry yes the current version works with my script. Thanks.

What I'm doing is different than "Render Animation with scene camera" (I only care about the active camera on the timeline not a render of all cameras at all points).  But that discussion isn't related to this bug..

**Comment by Gatada** [comment]
Yeah, and that is exactly what the new button does 😀 It doesn't render the sequence, just one camera: the currently active scene camera.

At least—If I understand you correctly:

• render current frame range
• using current active scene camera

So, for example:

Camera A - 1080 × 1080
Camera B - 1920 × 1080 (active)

Rendering range Start: 120
Rendering range End: 220

Hitting that new button in `[3D Viewport] > Cameras > Animation >  Render Scene Came` renders 100 frames using Camera B at 1920 × 1080 in a sub-folder called "Camera B" in your project's output folder, naming them 120.png, 121.png ... 220.png.

**Comment by mouring** [comment]
Not really.  

It renders *ALL* frames as "Camera B."  Where my timeline has frames 120 - 140 as Camera A as the active camera, and frames 141 - 220 as Camera B as the active camera.  My script steps through each frame, grabs the active camera (Camera bound to marker) for that frame, and renders it out.

Plus the button isn't useful for automated background pipeline work.  Where I'll need (in the future) to loop through at least 20 blender files to extract out a set of assets that may need further automated post processing so it can be autoloaded into the Godot project I'm toying with.   BTW this is very off topic on this ticket.  So I suspect either a new ticket should be filed or conversation happen outside the ticket.

**Comment by Gatada** [comment]
Thanks for clarifying; queueing of files. Nice.

But just want to point out that your desired functionality was there already in the UI, albeit for an open file:

1. Enable "Preview Sequence" in Animation.
2. Tap to render sequence with Eevee or Cycles.

It should be possible to do those steps in a script. Hm.. Maybe I'll make such a script and add it to the `readme.md`.

Or maybe you could share yours, so I could add that to help others?
